variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
    REGION: ap-northeast-1
    ECR_REPO: 873799242473.dkr.ecr.ap-northeast-1.amazonaws.com
    DOCKER_IMAGE: austin
    DOCKER_TAG: latest

cache:
    paths:
        - .cache/pip

stages:
    - test
    - docker_build

run_test:
    stage: test
    image: python:3.9-slim-buster
    before_script:
        - apt-get update && apt-get -y install make git
    script:
        - make test

build_image:
    stage: docker_build
    image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
    script:
        - aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin $ECR_REPO
        - docker build -t $DOCKER_IMAGE:$DOCKER_TAG .
        - docker push $ECR_REPO/$DOCKER_IMAGE:$DOCKER_TAG
