variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
    paths:
        - .cache/pip

run_test:
    image: python:3.9-slim-buster
    before_script:
        - apt-get update && apt-get -y install make
    script:
        - mkae test
