variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
    REGION: ap-northeast-1
    ECR_REPO: 873799242473.dkr.ecr.ap-northeast-1.amazonaws.com
    DOCKERIMAGE: python
    DOCKERTAG: ver1

cache:
    paths:
        - .cache/pip

run_test:
    image: python:3.9-slim-buster
    before_script:
        - apt-get update && apt-get -y install make git
    script:
        - make test

build_image:
    before_script:
        - pip3 install awscli --upgrade --user
    script:
        - aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin $ECR_REPO
        - docker build -t DOCKERIMAGE:DOCKERTAG .
        - docker push ECR_REPO/DOCKERIMAGE:DOCKERIMAGE
